### ISSUE TITLE
Add env vars to the Dockerfile to set the cli args

### ISSUE THREAD

**Issue by nwneisen** [nwneisen/dex-http-server#10]
#9 added the ability to configure the server address via cli args. We should modify the `Dockerfile` to use these.

The Dockerfile should set default values using `ENV`. These can `localhost:9090` for the gRPC server and port `8080` for the HTTP server.

The `docker-compose` file should then be configured to override these default values
```
services:
  dex-http-server:
    environment:
      - <http server port>=8080
      - <gRPc server address>=localhost:9090
```

We will still use the default values in the docker compose file but this makes it move obvious that we are setup to override these. The env var names can be whatever makes sense.
